import type {
  SceneGenqlSelection,
  PerformerGenqlSelection,
  StudioGenqlSelection,
  TagGenqlSelection,
  GalleryGenqlSelection,
  GroupGenqlSelection,
  ImageGenqlSelection,
} from './generated/index.js'

const TagSummary = { id: true, name: true } as const
const StashIDSummary = { endpoint: true, stash_id: true } as const
const StudioSummary = { id: true, name: true } as const
const PerformerSummary = { id: true, name: true, gender: true } as const

export const SceneFields = {
  id: true,
  title: true,
  code: true,
  date: true,
  details: true,
  director: true,
  interactive: true,
  interactive_speed: true,
  last_played_at: true,
  o_counter: true,
  o_history: true,
  organized: true,
  play_count: true,
  play_duration: true,
  play_history: true,
  rating100: true,
  resume_time: true,
  created_at: true,
  updated_at: true,
  urls: true,
  studio: StudioSummary,
  performers: PerformerSummary,
  tags: TagSummary,
  stash_ids: StashIDSummary,
} as const satisfies SceneGenqlSelection

export const PerformerFields = {
  id: true,
  name: true,
  disambiguation: true,
  alias_list: true,
  gender: true,
  birthdate: true,
  death_date: true,
  country: true,
  ethnicity: true,
  eye_color: true,
  hair_color: true,
  height_cm: true,
  weight: true,
  measurements: true,
  fake_tits: true,
  penis_length: true,
  circumcised: true,
  tattoos: true,
  piercings: true,
  career_length: true,
  details: true,
  favorite: true,
  ignore_auto_tag: true,
  image_path: true,
  rating100: true,
  o_counter: true,
  scene_count: true,
  image_count: true,
  gallery_count: true,
  group_count: true,
  performer_count: true,
  custom_fields: true,
  created_at: true,
  updated_at: true,
  urls: true,
  tags: TagSummary,
  stash_ids: StashIDSummary,
} as const satisfies PerformerGenqlSelection

export const StudioFields = {
  id: true,
  name: true,
  aliases: true,
  details: true,
  favorite: true,
  ignore_auto_tag: true,
  image_path: true,
  rating100: true,
  o_counter: true,
  scene_count: true,
  image_count: true,
  gallery_count: true,
  group_count: true,
  performer_count: true,
  created_at: true,
  updated_at: true,
  urls: true,
  parent_studio: StudioSummary,
  tags: TagSummary,
  stash_ids: StashIDSummary,
} as const satisfies StudioGenqlSelection

export const TagFields = {
  id: true,
  name: true,
  aliases: true,
  description: true,
  favorite: true,
  ignore_auto_tag: true,
  image_path: true,
  sort_name: true,
  child_count: true,
  parent_count: true,
  scene_count: true,
  scene_marker_count: true,
  image_count: true,
  gallery_count: true,
  group_count: true,
  performer_count: true,
  studio_count: true,
  created_at: true,
  updated_at: true,
  parents: TagSummary,
  children: TagSummary,
  stash_ids: StashIDSummary,
} as const satisfies TagGenqlSelection

export const GalleryFields = {
  id: true,
  title: true,
  code: true,
  date: true,
  details: true,
  photographer: true,
  organized: true,
  rating100: true,
  image_count: true,
  created_at: true,
  updated_at: true,
  urls: true,
  studio: StudioSummary,
  performers: PerformerSummary,
  tags: TagSummary,
} as const satisfies GalleryGenqlSelection

export const GroupFields = {
  id: true,
  name: true,
  aliases: true,
  date: true,
  director: true,
  duration: true,
  synopsis: true,
  front_image_path: true,
  back_image_path: true,
  rating100: true,
  o_counter: true,
  scene_count: true,
  sub_group_count: true,
  performer_count: true,
  created_at: true,
  updated_at: true,
  urls: true,
  studio: StudioSummary,
  tags: TagSummary,
} as const satisfies GroupGenqlSelection

export const ImageFields = {
  id: true,
  title: true,
  code: true,
  date: true,
  details: true,
  photographer: true,
  organized: true,
  rating100: true,
  o_counter: true,
  created_at: true,
  updated_at: true,
  urls: true,
  studio: StudioSummary,
  performers: PerformerSummary,
  tags: TagSummary,
} as const satisfies ImageGenqlSelection
